services:

  dev:
    build: ./docker/dev
    command: sleep infinity
    volumes:
      - .:/demo-opentelemetry-php
    working_dir: /demo-opentelemetry-php

      
  matemamusic-fpm:
    build: ./docker/fpm
    volumes:
      - ./matemamusic:/var/www
  
  matemamusic-nginx:
    build: ./docker/matemamusic-nginx
    volumes:
      - ./matemamusic:/var/www
    depends_on:
      - matemamusic-fpm
    ports:
      - 80:80

  user-svc-fpm:
    build: ./docker/fpm
    volumes:
      - ./user-svc:/var/www
  
  user-svc-nginx:
    build: ./docker/user-svc-nginx
    volumes:
      - ./user-svc:/var/www
    depends_on:
      - user-svc-fpm

  catalog-svc-fpm:
    build: ./docker/fpm
    volumes:
      - ./catalog-svc:/var/www
  
  catalog-svc-nginx:
    build: ./docker/catalog-svc-nginx
    volumes:
      - ./catalog-svc:/var/www
    depends_on:
      - catalog-svc-fpm

  playlist-svc-fpm:
    build: ./docker/fpm
    volumes:
      - ./playlist-svc:/var/www
  
  playlist-svc-nginx:
    build: ./docker/playlist-svc-nginx
    volumes:
      - ./playlist-svc:/var/www
    depends_on:
      - playlist-svc-fpm
