volumes:
  catalog-svc-data:
  playlist-svc-data:
  user-svc-data:

services:

  dev:
    build: ./docker/dev
    command: sleep infinity
    volumes:
      - .:/demo-opentelemetry-php
    working_dir: /demo-opentelemetry-php

      
  matemamusic-fpm:
    build: ./docker/fpm
    volumes:
      - ./matemamusic:/var/www
  
  matemamusic-nginx:
    build: ./docker/matemamusic-nginx
    volumes:
      - ./matemamusic:/var/www
    depends_on:
      - matemamusic-fpm
    ports:
      - 80:80

  user-svc-db:
    image: postgres:16
    shm_size: 128mb
    volumes:
      - user-svc-data:/var/lib/postgresql/data
      - ./user-svc/sql-init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgres-user

  user-svc-fpm:
    build: ./docker/fpm
    volumes:
      - ./user-svc:/var/www
    depends_on:
      - user-svc-db
  
  user-svc-nginx:
    build: ./docker/user-svc-nginx
    volumes:
      - ./user-svc:/var/www
    depends_on:
      - user-svc-fpm

  catalog-svc-db:
    image: postgres:16
    shm_size: 128mb
    volumes:
      - catalog-svc-data:/var/lib/postgresql/data
      - ./catalog-svc/sql-init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgres-catalog

  catalog-svc-fpm:
    build: ./docker/fpm
    volumes:
      - ./catalog-svc:/var/www
    depends_on:
      - catalog-svc-db
  
  catalog-svc-nginx:
    build: ./docker/catalog-svc-nginx
    volumes:
      - ./catalog-svc:/var/www
    depends_on:
      - catalog-svc-fpm

  playlist-svc-db:
    image: postgres:16
    shm_size: 128mb
    volumes:
      - playlist-svc-data:/var/lib/postgresql/data
      - ./playlist-svc/sql-init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgres-playlist

  playlist-svc-fpm:
    build: ./docker/fpm
    volumes:
      - ./playlist-svc:/var/www
    depends_on:
      - playlist-svc-db
  
  playlist-svc-nginx:
    build: ./docker/playlist-svc-nginx
    volumes:
      - ./playlist-svc:/var/www
    depends_on:
      - playlist-svc-fpm
