volumes:
  catalog-svc-data:
  favlist-svc-data:
  user-svc-data:

services:

  dev:
    build: ./docker/dev
    command: sleep infinity
    volumes:
      # In order to use the same user as the host shell
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - .:/demo-opentelemetry-php
    user: $UID:$GID
    working_dir: /demo-opentelemetry-php
    tmpfs:
      - $HOME/.composer

  lesfilmsquejekiffe-fpm:
    build: ./docker/fpm
    volumes:
      - ./lesfilmsquejekiffe:/var/www
    #environment:
    #  OTEL_EXPORTER_OTLP_ENDPOINT: "http://lgtm:4318"
    #  OTEL_PHP_AUTOLOAD_ENABLED: "true"
    #  OTEL_SERVICE_NAME: "lesfilmsquejekiffe-svc"
    #  OTEL_TRACES_EXPORTER: "otlp"
    #  OTEL_METRICS_EXPORTER: "otlp"
    #  OTEL_LOGS_EXPORTER: "otlp"
    #  OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
    #  OTEL_PROPAGATORS: "baggage,tracecontext"

  lesfilmsquejekiffe-nginx:
    build: ./docker/lesfilmsquejekiffe-nginx
    volumes:
      - ./lesfilmsquejekiffe:/var/www
    depends_on:
      - lesfilmsquejekiffe-fpm
    ports:
      - 80:80

  user-svc-db:
    image: postgres:16
    shm_size: 128mb
    volumes:
      - user-svc-data:/var/lib/postgresql/data
      - ./user-svc/sql-init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgres-user

  user-svc-fpm:
    build: ./docker/fpm
    volumes:
      - ./user-svc:/var/www
    depends_on:
      - user-svc-db
    #environment:
    #  OTEL_EXPORTER_OTLP_ENDPOINT: "http://lgtm:4318"
    #  OTEL_PHP_AUTOLOAD_ENABLED: "true"
    #  OTEL_SERVICE_NAME: "user-svc"
    #  OTEL_TRACES_EXPORTER: "otlp"
    #  OTEL_METRICS_EXPORTER: "otlp"
    #  OTEL_LOGS_EXPORTER: "otlp"
    #  OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
    #  OTEL_PROPAGATORS: "baggage,tracecontext"
  
  user-svc-nginx:
    build: ./docker/user-svc-nginx
    volumes:
      - ./user-svc:/var/www
    depends_on:
      - user-svc-fpm

  catalog-svc-db:
    image: postgres:16
    shm_size: 128mb
    volumes:
      - catalog-svc-data:/var/lib/postgresql/data
      - ./catalog-svc/sql-init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgres-catalog

  catalog-svc-fpm:
    build: ./docker/fpm
    volumes:
      - ./catalog-svc:/var/www
    depends_on:
      - catalog-svc-db
    #environment:
    #  OTEL_EXPORTER_OTLP_ENDPOINT: "http://lgtm:4318"
    #  OTEL_PHP_AUTOLOAD_ENABLED: "true"
    #  OTEL_SERVICE_NAME: "catalog-svc"
    #  OTEL_TRACES_EXPORTER: "otlp"
    #  OTEL_METRICS_EXPORTER: "otlp"
    #  OTEL_LOGS_EXPORTER: "otlp"
    #  OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
    #  OTEL_PROPAGATORS: "baggage,tracecontext"
  
  catalog-svc-nginx:
    build: ./docker/catalog-svc-nginx
    volumes:
      - ./catalog-svc:/var/www
    depends_on:
      - catalog-svc-fpm

  favlist-svc-db:
    image: postgres:16
    shm_size: 128mb
    volumes:
      - favlist-svc-data:/var/lib/postgresql/data
      - ./favlist-svc/sql-init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgres-favlist

  favlist-svc-fpm:
    build: ./docker/fpm
    volumes:
      - ./favlist-svc:/var/www
    depends_on:
      - favlist-svc-db
    #environment:
    #  OTEL_EXPORTER_OTLP_ENDPOINT: "http://lgtm:4318"
    #  OTEL_PHP_AUTOLOAD_ENABLED: "true"
    #  OTEL_SERVICE_NAME: "favlist-svc"
    #  OTEL_TRACES_EXPORTER: "otlp"
    #  OTEL_METRICS_EXPORTER: "otlp"
    #  OTEL_LOGS_EXPORTER: "otlp"
    #  OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
    #  OTEL_PROPAGATORS: "baggage,tracecontext"
  
  favlist-svc-nginx:
    build: ./docker/favlist-svc-nginx
    volumes:
      - ./favlist-svc:/var/www
    depends_on:
      - favlist-svc-fpm

#  lgtm:
#    image: grafana/otel-lgtm
#    ports: ["3000:3000"]
